## Vectorization First Example

In [1]:
import numpy as np
import time

In [13]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

start = time.time()
c = np.dot(a,b)
end = time.time()
print('Result ' + str(c) + ', Vectorized time ' + str((end-start)*1000) + " ms")

c = 0
start = time.time()
for i in range(1000000):
    c += a[i]*b[i]
end = time.time()
print('Result ' + str(c) + ', Loop time '+str((end-start)*1000) + " ms")

Result 249848.73689800446, Vectorized time 2.40325927734375 ms
Result 249848.73689800262, Loop time 696.2761878967285 ms


## Vectorization Other examples

In [ ]:
np.zeros((5,2))
np.exp()
np.log()
np.abs()
np.maximum()

## Broadcasting Example

In [4]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal = A.sum(axis=0) #add vertically
print(cal)

[ 59.  239.  155.4  76.9]


In [10]:
print(cal.shape)
print(cal.T.shape)

(4,)
(4,)


In [8]:
percentage = 100*A/cal.reshape(1,4) #(4,1) shape will not work
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [12]:
percentage = 100*A/cal.reshape(4,1)
print(percentage)

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

## Note on Numpy Vectors

**The following is bad coding practice for initializing numpy array**

In [13]:
#will return 5 random values from normal(Gaussian) distribution
#with mean 0 and variance 1
a = np.random.randn(5) 

In [14]:
#this shape is rank 1 array. So it's neither a row vector
#nor a column vector
print(a.shape)

(5,)


**Instead, initialize in this way**

In [15]:
a = np.random.randn(5,1)
print(a)

[[ 0.32191191]
 [ 2.04763078]
 [-0.56791537]
 [ 1.39466312]
 [-0.54917771]]


In [16]:
print(a.T)

[[ 0.32191191  2.04763078 -0.56791537  1.39466312 -0.54917771]]


In [6]:
a = np.random.rand(4,3)
b = np.random.rand(3,2)
c = np.dot(a,b)
print(c)
print(c.shape)

[[0.49050837 0.29422399]
 [0.53609198 0.28365445]
 [0.60094363 0.26960119]
 [0.50004892 0.42160194]]
(4, 2)


In [8]:
c = a*b
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

### L1 and L2 Loss

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [11]:
L1loss = np.sum(abs(a-b))
print(L1loss)

9


In [12]:
L2loss = np.dot((a-b),(a-b))
print(L2loss)

27
